package models;

public enum EventType {
    LOGIN, BAD_LOGIN, REGISTER, LOGOUT, PROVIDER_LINK, PROVIDER_UNLINK, CHANGE_PASSWORD, CHANGE_EMAIL, ADD_UPDATE_USER_API, RESET_PASSWORD_SEND, RESET_PASSWORD_COMPLETE
}
